name: Web Scraping Job

on:
  push:  # Executa sempre que você fizer um push no repositório
    branches:
      - main  # Altere para o nome da sua branch principal, se necessário

jobs:
  run-scraping:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Instalar o Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      # Passo 5: Instalar o Chromedriver
      - name: Install Chromedriver
        run: |
          # Baixar uma versão fixa do Chromedriver
          CHROMEDRIVER_VERSION="114.0.5735.90"
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          
          # Descompactar o Chromedriver
          unzip chromedriver_linux64.zip
          
          # Adicionar o Chromedriver ao PATH
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      # Passo 6: Executar o script de web scraping
      - name: Run scraping script
        env:
          MERCOS_EMAIL: ${{ secrets.MERCOS_EMAIL }}
          MERCOS_SENHA: ${{ secrets.MERCOS_SENHA }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python src/api/mercos_github.py