name: Web Scraping Job

on:
  push:
    branches:
      - main

jobs:
  run-scraping:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome:latest
      options: --user root  # Adicione esta linha para usar o root no container

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Executar o script
      - name: Run scraping script
        env:
          MERCOS_EMAIL: ${{ secrets.MERCOS_EMAIL }}
          MERCOS_SENHA: ${{ secrets.MERCOS_SENHA }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          chmod -R 777 /__w  # Ajustar permissões do diretório de trabalho
          python src/api/mercos_github.py