name: Web Scraping Job

on:
  push:  # Executa sempre que você fizer um push no repositório
    branches:
      - main  # Altere para o nome da sua branch principal, se necessário

jobs:
  run-scraping:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Instalar o Google Chrome
      - name: Install Google Chrome
        run: |
          # Instalar uma versão estável do Chrome (ex.: 114)
          sudo apt update
          sudo apt install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt --fix-broken install -y

      # Passo 5: Instalar o Chromedriver
      - name: Install Chromedriver
        run: |
          # Obter a versão principal do Chrome instalado
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          CHROME_VERSION_SHORT=$(echo $CHROME_VERSION | cut -d '.' -f -3)
          
          # Buscar a versão mais recente do Chromedriver compatível
          CHROMEDRIVER_RELEASE_URL="https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION_SHORT"
          CHROMEDRIVER_VERSION=$(curl -s $CHROMEDRIVER_RELEASE_URL)
          
          # Corrigir URL para evitar caracteres especiais
          CHROMEDRIVER_DOWNLOAD_URL="https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          
          # Baixar e configurar o Chromedriver
          wget $CHROMEDRIVER_DOWNLOAD_URL
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      # Passo 6: Executar o script de web scraping
      - name: Run scraping script
        env:
          MERCOS_EMAIL: ${{ secrets.MERCOS_EMAIL }}
          MERCOS_SENHA: ${{ secrets.MERCOS_SENHA }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python src/api/mercos_github.py