name: Web Scraping Job

on:
  push:
    branches:
      - main

jobs:
  run-scraping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install Chromedriver
        run: |
          # Obter a versão do Chrome instalado
          CHROME_VERSION=$(google-chrome --version | awk '{ print $3 }' | cut -d'.' -f1-3)
          echo "Chrome version: $CHROME_VERSION"
          
          # Determinar a versão mais recente do ChromeDriver compatível
          CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
          
          # Baixar o ChromeDriver
          wget -O chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          
          # Verificar se o download foi bem-sucedido
          if [ ! -f chromedriver_linux64.zip ]; then
            echo "Falha no download do ChromeDriver"
            exit 1
          fi
          
          # Descompactar o ChromeDriver
          unzip chromedriver_linux64.zip
          
          # Verificar se o arquivo chromedriver existe
          if [ ! -f chromedriver ]; then
            echo "Falha na extração do ChromeDriver"
            exit 1
          fi
          
          # Adicionar o ChromeDriver ao PATH
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          
          # Verificar a instalação
          chromedriver --version         

      - name: Run scraping script
        env:
          MERCOS_EMAIL: ${{ secrets.MERCOS_EMAIL }}
          MERCOS_SENHA: ${{ secrets.MERCOS_SENHA }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python mercos_github.py